RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
BOOTMAGIC_ENABLE = no

OLED_ENABLE = yes
WPM_ENABLE = no

TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
UNICODE_ENABLE  = no

POINTING_DEVICE_ENABLE = yes

#ifdef POINTING_DEVICE_ENABLE
  POINTING_DEVICE_DRIVER = pimoroni_trackball
#endif

LTO_ENABLE= yes
NO_DEBUG = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
