RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no

OLED_ENABLE = no
WPM_ENABLE = no

#ifdef OLED_ENABLE
  WPM_ENABLE = yes
#endif

TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
UNICODE_ENABLE  = no

POINTING_DEVICE_ENABLE = yes

#ifdef POINTING_DEVICE_ENABLE
  POINTING_DEVICE_DRIVER = pimoroni_trackball
#endif

LTO_ENABLE      = yes
CONSOLE_ENABLE  = no
NO_DEBUG = yes
EXTRAKEY_ENABLE = no
