RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no

POINTING_DEVICE_ENABLE = yes

OLED_ENABLE = yes

TAP_DANCE_ENABLE = yes

LTO_ENABLE = yes
NO_DEBUG = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
