CONSOLE_ENABLE = yes
CUSTOM_MATRIX = lite
# SRC += matrix.c i2c2_handler.c
SRC += ps2.c
# I2C_DRIVER_REQUIRED = yes

# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = azoteq_iqs5xx

I2C_ENABLE = no
PS2_ENABLE = yes
PS2_MOUSE_ENABLE = yes
PS2_DRIVER = interrupt
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
