INTROSPECTION_KEYMAP_C = tcy.c

SRC += users/tcy/tapdance.c

EXTRAFLAGS += -Iusers/tcy

TAP_DANCE_ENABLE = yes

ifdef OLED_ENABLE_MINIMAL
OLED_ENABLE = yes
OPT_DEFS += -DOLED_ENABLE_MINIMAL
endif

PS2_MIN_ACCELERATION_SETTING = 1
PS2_MAX_ACCELERATION_SETTING = 6
PS2_DEFAULT_ACCELERATION_SETTING = 5
OPT_DEFS += -DPS2_MIN_ACCELERATION_SETTING=$(PS2_MIN_ACCELERATION_SETTING)
OPT_DEFS += -DPS2_MAX_ACCELERATION_SETTING=$(PS2_MAX_ACCELERATION_SETTING)
OPT_DEFS += -DPS2_DEFAULT_ACCELERATION_SETTING=$(PS2_DEFAULT_ACCELERATION_SETTING)

POINTING_DEVICE_DEFAULT_CPI = 350
POINTING_DEVICE_MAX_CPI = 800
OPT_DEFS += -DPOINTING_DEVICE_DEFAULT_CPI=$(POINTING_DEVICE_DEFAULT_CPI)
OPT_DEFS += -DPOINTING_DEVICE_MAX_CPI=$(POINTING_DEVICE_MAX_CPI)

OPT_DEFS += -DPOINTING_LEFT_DEVICE_DEFAULT_CPI=$(POINTING_LEFT_DEVICE_DEFAULT_CPI)
OPT_DEFS += -DPOINTING_RIGHT_DEVICE_DEFAULT_CPI=$(POINTING_RIGHT_DEVICE_DEFAULT_CPI)

WPM_ENABLE = yes
EEPROM_ENABLE = no

OPT_DEFS += -DTCY_FULL_TD

# QMK default is 3; with this many holdable tap dances (TD_ENT/TD_A/TD_ESC/
# thumbs/word-nav) three held dances are realistic, and a 4th TD press is then
# silently dropped by process_tap_dance. Each extra slot costs ~10 bytes RAM.
OPT_DEFS += -DTAP_DANCE_MAX_SIMULTANEOUS=8
