INTROSPECTION_KEYMAP_C = tcy.c

SRC += users/tcy/tapdance.c

EXTRAFLAGS += -Iusers/tcy

TAP_DANCE_ENABLE = yes

ifdef OLED_ENABLE_MINIMAL
OLED_ENABLE = yes
OPT_DEFS += -DOLED_ENABLE_MINIMAL
endif

PS2_MIN_ACCELERATION_SETTING = 1
PS2_MAX_ACCELERATION_SETTING = 6
PS2_DEFAULT_ACCELERATION_SETTING = 5
OPT_DEFS += -DPS2_MIN_ACCELERATION_SETTING
OPT_DEFS += -DPS2_MAX_ACCELERATION_SETTING
OPT_DEFS += -DPS2_DEFAULT_ACCELERATION_SETTING
