VIA_ENABLE = no
ENCODER_MAP_ENABLE = yes
BOOTMAGIC_ENABLE = no   # Enable Bootmagic Lite
EXTRAKEY_ENABLE = no    # Audio control and System control
CONSOLE_ENABLE = no     # Console for debug
COMMAND_ENABLE = no     # Commands for debug and configuration
NKRO_ENABLE = yes       # USB Nkey Rollover
LTO_ENABLE = no
OLED_ENABLE = no
