#pragma once

/* place override params */
#define DYNAMIC_KEYMAP_LAYER_COUNT 10

#define POINTING_DEVICE_ROTATION_90
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_TASK_THROTTLE_MS 8

#undef I2C1_SCL_PIN
#define I2C1_SCL_PIN D0

#undef I2C1_SDA_PIN
#define I2C1_SDA_PIN D1
