#pragma once


#define MASTER_RIGHT

#define SPLIT_ACTIVITY_ENABLE
#define SPLIT_TRANSPORT_MIRROR

#undef ENCODER_RESOLUTION
#define ENCODER_RESOLUTIONS_RIGHT { 1, 1 }

#define POINTING_DEVICE_RIGHT
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_TASK_THROTTLE_MS 8
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_DIAMETER_MM	40
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_3X

#define SERIAL_USE_MULTI_TRANSACTION
