DEFAULT_FOLDER = crkbd_rp2040/rev1

# reduce bundle size
LTO_ENABLE = no
EXTRAFLAGS += -flto

VIA_ENABLE = no
TAP_DANCE_ENABLE = no
UNICODE_ENABLE  = no
MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
SERIAL_DRIVER = vendor
