# Build Options
#   change yes to no to disable
#

DEFAULT_FOLDER = crkbd/rev1

# reduce bundle size
LTO_ENABLE = yes
EXTRAFLAGS += -flto

VIA_ENABLE = no
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE  = no
MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_SUPPORTED = yes
RGB_MATRIX_SUPPORTED = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
NO_DEBUG = yes
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
